version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: frankenstein-service
    environment:
      POSTGRES_USER: frankenstein
      POSTGRES_PASSWORD: frankenstein
      POSTGRES_DB: frankenstein
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: